octagon_shoe_portal_admin:
    resource:  "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/
    
octagon_shoe_portal_customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

