# app/config/security.yml
security:
    firewalls:
        login_firewall:
            pattern:   ^/security/login$
            anonymous: ~
        secured_area:
            pattern:   ^/
            anonymous: ~
            logout:
                path:   _logout
                target: /
            form_login:
                login_path: _login
                check_path: _login_check
                success_handler: security.authentication.success_handler
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Include the following line to also secure the /admin path itself

    providers:
         main:
            entity:
                class: Octagon\ShoePortal\CustomerBundle\Entity\User
                property: username

    encoders:
        Octagon\ShoePortal\CustomerBundle\Entity\User: 
           algorithm: sha256
           iterations: 1
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]