# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    
services:
#    ccdn_user_security.component.authentication.handler.login_failure_handler:
#        class:  %ccdn_user_security.component.authentication.handler.login_failure_handler.class%
#        arguments:  [@service_container, @router, @security.context]
#        tags:
#            - { name: 'monolog.logger', channel: 'security' } 
    security.authentication.success_handler:
        class:  Octagon\ShoePortal\CustomerBundle\Controller\AuthenticationSuccessHandler
        arguments:  [@router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    kernel.listener.custom_event_listener:
        class: Octagon\ShoePortal\CustomerBundle\Controller\ExceptionListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }