_home:
    path:     /
    defaults: { _controller: CustomerBundle:Home:home }

#Shoes
_shoes:
    path:     /shoes/list
    defaults: { _controller: CustomerBundle:Shoes:list }
_shoe:
    path:     /shoes/view
    defaults: { _controller: CustomerBundle:Shoes:view }
_shoe_edit:
    path:     /shoes/edit
    defaults: { _controller: CustomerBundle:Shoes:edit }
_shoe_add:
    path:     /shoes/add
    defaults: { _controller: CustomerBundle:Shoes:add }
_shoe_delete:
    path:     /shoes/delete
    defaults: { _controller: CustomerBundle:Shoes:delete } 
#Categories

_categories:
    path:     /categories/list
    defaults: { _controller: CustomerBundle:Categories:list }

#Security
_login:
    path:     /security/login
    defaults: { _controller: CustomerBundle:Security:login }
    
_login_check:
    path: /security/login_check

_logout:
    path: /security/logout   
#Users
_register:
    path:     /users/register
    defaults: { _controller: CustomerBundle:Users:register }
_user:
    path:     /users/view
    defaults: { _controller: CustomerBundle:Users:view}
_edit:
    path: /users/edit
    defaults: { _controller: CustomerBundle:Users:edit}
    
_block:
    path: /users/block
    defaults: { _controller: CustomerBundle:Users:block}
    